volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-api
      - programming-ui
    ports:
      - 7800:7800

  programming-api:
    build: programming-api
    image: programming-api
    restart: "no"
    volumes:
      - ./programming-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database-test
      - flyway
      - redis
    env_file:
      - test.env

  programming-ui:
    build: programming-ui
    image: programming-ui
    restart: "no"
    volumes:
      - ./programming-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - programming-api

  grader-api:
    build: grader-api
    image: grader-api
    restart: "no"
    volumes:
      - ./grader-api/:/app
      - ./app-cache/:/app-cache
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000

  database-test:
    container_name: database-test-server
    image: postgres:14.1
    restart: "no"
    env_file:
      - test.env

  flyway:
    image: flyway/flyway:10.18.0
    depends_on:
      - database-test
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - test.env

  playwright:
    entrypoint: "/bin/true"
    build: playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./playwright/tests:/app/tests
  
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
